-- lib/clickhouse/ddl.sql — POINTER ONLY, not a schema.
--
-- The authoritative warehouse DDL lives at:
--   docs/specs/2026-07-05-warehouse-schema-v2.sql   (v2 — snapshot / _history / _stat)
--
-- Apply that file manually per environment (statements are CREATE TABLE IF NOT EXISTS;
-- ClickHouse Cloud auto-rewrites the MergeTree family to Shared*).
--
-- Do NOT add CREATE TABLE statements here. New tables must pass the E2.2 decision tree
-- (docs/plans/2026-07-09-master-task-plan.md) and land in the v2 spec only.
--
-- Drift check (live cluster vs v2 spec):  pnpm check:drift
-- Last verified 2026-07-10 — 31/31 tables, zero column/type/key drift (task 2.1.2).
